### PR TITLE
chore: update dependencies, node version and remove travis config [BD-38]

### PR DESCRIPTION
**Pull request by xitij2000**
Update dependencies
Update node version
Remove travis config

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @xitij2000! I've created [BLENDED-955](https://openedx.atlassian.net/browse/BLENDED-955) to keep track of it in Jira.   More details are on the [BD-38](https://openedx.atlassian.net/wiki/spaces/COMM/pages/2790490201/BD-38+Discussions+In-Context+Discussion+Moderation+Phase+2) project page.


When this pull request is ready, tag your edX technical lead.

**Review by mehaknasir — APPROVED** [review]

**Comment by AhtishamShahid** [comment]
Are you tracking this work under a TNL ticket? If not can you create it?

**Review by awais-ansari — APPROVED** [review]

**Comment by xitij2000** [comment]
> Are you tracking this work under a TNL ticket? If not can you create it?

This is just a dependency upgrade. I can track it as part of an existing ticket but it's mainly because this bit isn't automated yet.

**Comment by edx-webhook** [comment]
@xitij2000 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/frontend-app-discussions&entry.867055334=https://github.com/edx/frontend-app-discussions/pull/16&entry.1484655318=https://github.com/xitij2000&entry.752974735=2021-09-06+11:01&entry.1917517419=2021-09-14+12:11&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
