### PR TITLE
[BD-38][TNL-8428] feat: Implement post search.

### PR DESCRIPTION
**Pull request by kewne**
Typing into the  "Search all posts" box now works as intended, affecting the "My Posts" and "All Posts" lists.

Related tickets:
* [TNL-8428](https://openedx.atlassian.net/browse/TNL-8428)
* [BB-4418 (OpenCraft Internal)](https://tasks.opencraft.com/browse/BB-4418)

# Testing

1. Open discussion MFE for demo course
2. Type into "Search all posts" box and press Enter
tnl8428_bb4418_search_box
3. Verify that "All Posts" and "My Posts" lists only show matching posts.

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @kewne! I've created [BLENDED-921](https://openedx.atlassian.net/browse/BLENDED-921) to keep track of it in Jira.


When this pull request is ready, tag your edX technical lead.

**Review by xitij2000 — APPROVED** [review]
:+1:
- [x] I tested this: tested against master branch of edx-platform
- [x] I read through the code
- [x] I checked for accessibility issues
- [na] Includes documentation

**Comment by mehaknasir** [comment]
@kewne can you please add a description on PR as well along with ticket ids. Thanks

**Review by mehaknasir — APPROVED** [review]

**Comment by asadazam93** [comment]
@kewne Is this ready to be merged? If yes, should I merge it?

**Comment by kewne** [comment]
@asadazam93 I think it can be merged, yes. Thanks!

**Review by awaisdar001 — APPROVED** [review]

**Pull request merged**
