### PR TITLE
test: add simple test for DiscussionsHome [BD-38] [TNL-8696] [BB-4842]

### PR DESCRIPTION
**Pull request by Cup0fCoffee**
## Description

This PR adds tests boilerplate code and a single basic test for DiscussionsHome component.

### CODE REVIEW

**Comment by mehaknasir** [comment]
> > I don't feel like this PR covers all the test cases for the Discussions home page. we have multiple actions here and I feel like we should then test all of them.
> > It seems incomplete to me.
> 
> @mehaknasir Originally, this change was part of the bigger PR, which was broken up into smaller PRs to make it easier to merge. As of right now, I'm not sure if we have plans on adding anything to this PR (it's better to ask @xitij2000). Imho, this PR is still worth merging as it is, because it's already has the necessary boilerplate created, which will reduce friction in the future, i.e. it's easier to add tests to existing test suit, than having to write it from scratch.

@Cup0fCoffee - I agree that the done work is okay, but according to description of the PR it says adding test cases for discussions home page.

we have the following actions on the home page which filter content

- all topics 
- my posts
- all posts
- search bar
- list rendering in the side menu
- posts edit/create view

It creates multiple test cases for all these components.

either we can update the description of the PR. and create a follow-up ticket to cover the actual set of test cases or we can update PR with all  the needed test cases let me know what you think?

**Comment by Cup0fCoffee** [comment]
@mehaknasir I updated the PR description to more clearly explain that the PR adds tests bolierplate code and a single basic test.

**Review by awais-ansari — APPROVED** [review]

**Comment by awais-ansari** [comment]
> @mehaknasir I updated the PR description to more clearly explain that the PR adds tests boilerplate code and a single basic test.

@Cup0fCoffee if it's just a boilerplate then it's good to go.

**Review by mehaknasir — APPROVED** [review]
Approving as boilerplate for tests of for discussions home page. expecting extension in a future PR

**Comment by edx-webhook** [comment]
@Cup0fCoffee 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/frontend-app-discussions&entry.867055334=https://github.com/edx/frontend-app-discussions/pull/30&entry.1484655318=https://github.com/Cup0fCoffee&entry.752974735=2021-10-26+01:26&entry.1917517419=2021-11-02+11:53&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
