### PR TITLE
[WIP] [BD-03] [TNL-7353] Prototype: Create React-based forum post editor

### PR DESCRIPTION
**Pull request by 0x29a**
In this PR I replaced textarea in add post component with WYSIWYG editor based on https://github.com/jpuri/react-draft-wysiwyg which in turn based on https://draftjs.org/.

Relevant commit: https://github.com/edx/frontend-app-discussions/commit/ac5b9968b42c218009f53080afc1cf1f40c22d17

**JIRA tickets**:
- [TNL-7353](https://openedx.atlassian.net/browse/TNL-7353)

**Dependencies**:

This PR depends on a multiple other PRs which depends on each other:
https://github.com/edx/frontend-app-discussions/pull/6 -> https://github.com/edx/frontend-app-discussions/pull/2 -> https://github.com/edx/frontend-app-discussions/pull/1

**Screenshots**:
Screenshot from 2020-10-13 14-10-46

**Sandbox URL**: TBD

**Merge deadline**: None

**Testing instructions**:

1. Run LMS. It should have http://localhost:18000 address.
2. Clone https://github.com/open-craft/frontend-app-discussions repo, checkout to `0x29a/bb2970/post_editor` branch, install dependencies with `npm install`, run development server with `npm start`.
3. Go to http://localhost:2002/discussions/course-v1:edX+DemoX+Demo_Course/posts/mine.
4. Click `Add Post`.
5. Play with `Your question or idea` input.

**Author notes and concerns**:

1. I decided to use https://github.com/jpuri/react-draft-wysiwyg because implementing proper WYSIWYG editor from scratch on top of draft-js is for sure beyond the scope of this ticket.
2. If we want to show raw version of editor like on Github, we can use https://github.com/kadikraman/draftjs-md-converter library. We can also use it to get markdown representation of editor state, but there can be other alternatives.
3. Since this is a prototype, and we didn't implement all necessary thunks, it doesn't have features like uploading images. Also, it doesn't contain any styling.

**Reviewers**
- [ ] @shimulch
- [ ] edX reviewer[s] TBD

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @0x29a! I've created [BLENDED-631](https://openedx.atlassian.net/browse/BLENDED-631) to keep track of it in Jira.


When this pull request is ready, tag your edX technical lead.

**Review by shimulch — APPROVED** [review]
LGTM :+1:

- [x] I tested this locally
- [x] I read through the code
- [N/A] I checked for accessibility issues
- [N/A] Includes documentation
- [N/A] I made sure any change in configuration variables is reflected in the corresponding client's `configuration-secure` repository.

**Comment by e0d** [comment]
@0x29a is this PR still active?  Trying to review our backlog of un-merged code and this is a large part of that.

**Comment by 0x29a** [comment]
Hi @e0d, no, I don't think this PR is active. AFAIK, we've decided to use TinyMCE instead of `react-draft-wysiwyg`. I'll let @xitij2000 close this, if I'm not wrong.

**Pull request closed without merging**
